import {Canvas} from '@react-three/fiber';import {OrbitControls,Text} from '@react-three/drei';
import {useMemo} from 'react';import {COLORS,USE_LABELS} from '../data/scenarios';import type {Assignment} from '../types';import {useSim} from '../store/useSim';
function Street3D({assignments,onChoose}:{assignments:Assignment[];onChoose:(s:string)=>void}){
 const positions=useMemo(()=>assignments.map((_,i)=>[i%8,Math.floor(i/8)]),[assignments]);
 return <Canvas camera={{position:[10,16,20],fov:42}} shadows gl={{antialias:true}}><color attach="background" args={['#0c1928']}/><ambientLight intensity={1.4}/><directionalLight position={[5,12,7]} intensity={2}/><OrbitControls makeDefault minDistance={9} maxDistance={50} maxPolarAngle={Math.PI/2.05}/>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,-.24,0]}><planeGeometry args={[24,13]}/><meshStandardMaterial color="#15293a"/></mesh>
 <mesh position={[0,-.15,0]}><boxGeometry args={[19,.06,5.4]}/><meshStandardMaterial color="#263849"/></mesh>
 {Array.from({length:9},(_,i)=><mesh key={i} position={[-8+i*2, -.105,0]}><boxGeometry args={[1,.015,.045]}/><meshBasicMaterial color="#e7d5a8"/></mesh>)}
 {positions.map(([col,row],i)=>{const a=assignments[i];const x=(col-3.5)*2.15;const z=row===0?-3.4:3.4;return <group key={a.id} position={[x,0,z]}><mesh onClick={(e)=>{e.stopPropagation();onChoose(a.id)}} position={[0,.06,0]}><boxGeometry args={[2,.16,1.5]}/><meshStandardMaterial color={COLORS[a.use]} roughness={.55} emissive={COLORS[a.use]} emissiveIntensity={.12}/></mesh><Text position={[0,.2,0]} rotation={[-Math.PI/2,0,0]} fontSize={.3} color="#071321" anchorX="center">{a.id}</Text>{(a.use==='parking'||a.use==='delivery'||a.use==='bus'||a.use==='auto')&&<mesh position={[0,.32,0]}><boxGeometry args={[a.use==='bus'?1.5:1,.3,.58]}/><meshStandardMaterial color="#f1f5f9"/></mesh>}</group>})}
 {Array.from({length:10},(_,i)=><group key={i} position={[(i-4.5)*2.3,0,i%2===0?-6:6]}><mesh position={[0,.75,0]}><boxGeometry args={[1.6,1.5,1.6]}/><meshStandardMaterial color={i%2?'#40536f':'#2d4562'}/></mesh><mesh position={[0,1.52,0]}><boxGeometry args={[1.7,.08,1.7]}/><meshStandardMaterial color="#6bc9eb"/></mesh></group>)}
 </Canvas>
}
export function Road({assignments,compact=false}:{assignments:Assignment[];compact?:boolean}){const {selected,setSelected,view3d,set3d}=useSim();return <div className="roadPanel"><div className="roadToolbar"><div><span className="liveDot"/> DIGITAL CURB TWIN <small> • Simulated environment</small></div><div className="segmented"><button className={!view3d?'active':''} onClick={()=>set3d(false)}>2D</button><button className={view3d?'active':''} onClick={()=>set3d(true)}>3D</button></div></div><div className={compact?'roadCanvas compact':'roadCanvas'}>{view3d?<div className="threeWrap"><CanvasGuard assignments={assignments} onChoose={setSelected}/></div>:<div className="road2d"><div className="streetblock">NORTH CURB</div><div className="segmentGrid">{assignments.slice(0,Math.ceil(assignments.length/2)).map(a=><button key={a.id} onClick={()=>setSelected(a.id)} className={'segment '+(selected===a.id?'selected':'')} style={{background:COLORS[a.use]}} title={a.reason}><strong>{a.id}</strong><small>{a.use}</small></button>)}</div><div className="lane">↠ &nbsp; CITY STREET / TWO-WAY TRAFFIC &nbsp; ↠</div><div className="segmentGrid">{assignments.slice(Math.ceil(assignments.length/2)).map(a=><button key={a.id} onClick={()=>setSelected(a.id)} className={'segment '+(selected===a.id?'selected':'')} style={{background:COLORS[a.use]}} title={a.reason}><strong>{a.id}</strong><small>{a.use}</small></button>)}</div><div className="streetblock">SOUTH CURB</div></div>}</div><div className="legend">{Object.entries(COLORS).map(([k,color])=><span key={k}><i style={{background:color}}/>{USE_LABELS[k as keyof typeof USE_LABELS]}</span>)}</div></div>}
import React from 'react';
class Boundary extends React.Component<{children:React.ReactNode;fallback:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
function CanvasGuard({assignments,onChoose}:{assignments:Assignment[];onChoose:(s:string)=>void}){const set3d=useSim(s=>s.set3d);return <Boundary fallback={<div className="empty">WebGL unavailable. <button className="btn" onClick={()=>set3d(false)}>Open 2D road</button></div>}><Street3D assignments={assignments} onChoose={onChoose}/></Boundary>}
